title: Al-Amin's drafts
email: tokhandaker@outlook.com
description: >-
Welcome to my site.
I'm Al-Amin from a small village of Bangladesh now loving in one of the biggest citi's in the world, Tokyo.
I love learning new things. 
I am not good at documenting. 
This site is my try to note down what's going in my head.
baseurl: eNipu.github.io
twitter_username: eNipu
github_username: eNipu
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: JP # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Md. Al-Amin Khandaker"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Learner. Teach me something"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://al-amin.ninja"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eNipu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eNipu"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eNipu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eNipu"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
